# This workflow will install Python dependencies, run tests
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ${{ matrix.runs-on }}
    strategy:
      fail-fast: false
      matrix:        
        runs-on: [ubuntu-22.04, macos-latest, macos-14, macos-13, windows-latest ]
        python-version: [ 3.7, 3.8, 3.9, "3.10", "3.11" ]
        exclude:
          - runs-on: macos-latest
            python-version: "3.8"

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python  ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version:  ${{ matrix.python-version }}
        
    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements_dev.txt
        pip install -e .
        pip install -e examples/toy_dataset
        
    - name: Tests
      run: |
        python -V
        pip list
        wormpose -v
        PYTHONHASHSEED=0 wormpose calibrate toy toy_data  --random_seed 123
        PYTHONHASHSEED=0 wormpose datagen toy toy_data --num_train_samples 200 --num_eval_samples 200 --random_seed 123
        PYTHONHASHSEED=0 wormpose train toy_data --epochs 1 --random_seed 123
        PYTHONHASHSEED=0 wormpose predict toy_data --score_threshold 0.0 --random_seed 123
        wormpose postprocess toy_data
        wormpose viz toy_data
        PYTHONHASHSEED=0 wormpose evaluate toy_data --num_samples 10  --random_seed 123
        wormpose export toy_data

        
